baseURL = "https://rahulpnath.com/"
languageCode = "en-us"
title = "Rahul Nath"

# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

disqusShortname = "rahulpnath"

enableEmoji = true

pygmentsCodefences = true
pygmentsOptions = "linenos=true,nobackground=true"
pygmentsStyle = "monokailight"

Paginate = 5

[params.widgets]
homepage = ["recent_posts"]
sidebar = ["about","search","sidebar_menu","taxonomy_cloud"]
footer = ["social_menu"]

[taxonomies]
category = "categories"
tag = "tags"

[permalinks]
categories = "/blog/category/:title/"
tags = "/blog/tag/:title/"

[menu]
	[[menu.main]]
    identifier = "home"
    name = "home"
    url = "/"
    weight = -130